apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-mlnx-dpdk
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [
            {
                "resourceName": "mlnx_connectx4",
                "isRdma": true,
                "selectors": {
                    "vendors": ["15b3"],
                    "devices": ["1016"],
                    "drivers": ["mlx5_ib", "mlx5_core"]
                }
            },
            {
                "resourceName": "mlnx_connectx5",
                "isRdma": true,
                "selectors": {
                    "vendors": ["15b3"],
                    "devices": ["1018"],
                    "drivers": ["mlx5_ib", "mlx5_core"]
                }
            }
        ]
    }
