apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [
            {
                "resourcePrefix": "mellanox.com",
                "resourceName": "mlnx_connectx4",
                "selectors": {
                    "vendors": ["15b3"],
                    "devices": ["1016"],
                    "drivers": ["mlx5_core"],
                    "isRdma": true
                }
            },
            {
                "resourcePrefix": "mellanox.com",
                "resourceName": "mlnx_connectx5",
                "selectors": {
                    "vendors": ["15b3"],
                    "devices": ["1018"],
                    "drivers": ["mlx5_core"],
                    "isRdma": true
                }
            }
        ]
    }
